# 20250330 - just switching to process optimisation with diffusion now, and extending the diffusion time horizon

# Model
model_name: hvae_delayed_probe_cue_factorised_palimpsest_representation
model_config:
  recurrence_hidden_layers: [50]
  time_embedding_size: 16
  sample_ambient_dim: 50
  feature_projection_sizes: [6, 6]  # network input size is 36
  residual_model_kwargs:
    nonlin_first: false
  ddpm_model_kwargs:
    train_as_rnn: false
    noise_scaler: 'nat'
    seperate_output_neurons: false



regularise_prep_state: true
regularise_prep_state_weight: 0.001


regularise_prep_activity_indices: [0, 1, 2, 3]
regularise_prep_activity_weight: 0.0001
regularise_diffusion_nullspace: true


# Diffusion
ultimate_sigma2: 0.20
starting_sigma2: 0.20
num_timesteps: 30



# Training/logging
logging_freq: 1000
batch_size: 32
num_samples: 1024
num_trials: 10_000_000
lr: 0.001
save_base: "/homes/pr450/repos/research_projects/sampling_ddpm/results_link_sampler/hvae_with_bounceback_20250330/run_a3_probe_cued_hvae_flat_swap"


# resume_path: "/homes/pr450/repos/research_projects/sampling_ddpm/results_link_sampler/hvae_with_bounceback_20250330/run_a2_probe_cued_hvae_no_swap_long_0/state.mdl"
resume_path: "/homes/pr450/repos/research_projects/sampling_ddpm/results_link_sampler/hvae_with_bounceback_20250330/run_a3_probe_cued_hvae_flat_swap_0/state.mdl"


# Task
task_name: delayed_probe_cue_vectoral_spike_and_slab_palimpsest
task_config:

  probe_num_tc: 16
  report_num_tc: 16
  probe_tc_width: 5.0
  report_tc_width: 5.0

  vectorise_input: false

  sample_size: 2
  num_items: 2
  correct_probability: 0.8               # Increased vs previous cases
  residual_in_behaviour_plane_only: false
  sample_radius: 2.5

  stimulus_exposure_duration: 5
  pre_index_delay_duration: [15, 15]    # only diff
  index_duration: 5
  post_index_delay_duration: 1
