# 20250322

# Model
model_name: hvae_bounceback_delayed_probe_cue_factorised_palimpsest_representation
model_config:
  time_embedding_size: 16
  sample_ambient_dim: 50            # Linear projection between populations expected
  feature_projection_sizes: [6, 6]  # network input size is 36
  residual_model_kwargs: {}
  ddpm_model_kwargs:
    train_as_rnn: false
    noise_scaler: 'nat'
    seperate_output_neurons: false
    bounce_euler_alpha: 0.9
    bounce_noise_scalar: 0.5
    primary_euler_alpha: 0.1
    primary_noise_scalar: 1.0



regularise_prep_state: true
regularise_prep_state_weight: 0.01


regularise_prep_activity_indices: [0, 1, 2, 3]
regularise_prep_activity_weight: 0.00001
regularise_diffusion_nullspace: true


# Diffusion
ultimate_sigma2: 0.14   # Changed a bunch!
starting_sigma2: 0.14   # Changed a bunch!
num_timesteps: 40       # Changed!




# Training/logging
logging_freq: 1000
batch_size: 32
num_samples: 1024
num_trials: 10_000_000
lr: 0.005
save_base: "/homes/pr450/repos/research_projects/sampling_ddpm/results_link_sampler/hvae_with_bounceback_20250330/run_b2c_bounce_cyclical_swap"



resume_path: "/homes/pr450/repos/research_projects/sampling_ddpm/results_link_sampler/hvae_with_bounceback_20250330/run_b2b_bounce_flat_swap_more_1/state.mdl"



# Task
task_name: delayed_probe_cue_vectoral_with_swap_function_palimpsest
task_config:

  probe_num_tc: 16
  report_num_tc: 16
  probe_tc_width: 5.0
  report_tc_width: 5.0

  vectorise_input: false

  sample_size: 2
  num_items: 2
  swap_function_width: 1.5
  residual_in_behaviour_plane_only: false
  sample_radius: 2.5

  stimulus_exposure_duration: 5
  pre_index_delay_duration: [15, 15]
  index_duration: 5
  post_index_delay_duration: 1
