batch_size: 64
neurons: 32
load_path: ddpm/dynamical/logs/training/net.mdl

duration: 1.0
duration_no_stim: 5.0
tau: 0.1
dt: 0.001
k: 1.0
n: 1
# h_scale: 5e-2
h_scale: 1.0

sigma2_xi: 0.01

num_epochs: 10000000
num_mems: 5
