# 20250227
# Same as before but fewer items...

# python -m ddpm.train_multiepoch ddpm/configs/further_capabilities/b2_probe_cued_with_probe_flat_swap_fewer.yaml


# Model
model_name: standard_vectoral
model_config:
  
  recurrence_hidden_layers: [64, 64, 64]
  time_embedding_size: 16
    
  residual_model_kwargs:
    nonlin_first: false
  ddpm_model_kwargs:
    asdf: asdf


regularise_prep_state: false

# Diffusion
ultimate_sigma2: 0.20
starting_sigma2: 0.20
num_timesteps: 40

# Training/logging
logging_freq: 100
batch_size: 32
num_samples: 1024
num_trials: 10_000_000
lr: 0.001
save_base: "/homes/pr450/repos/research_projects/sampling_ddpm/results_link_sampler/ddpm_conjuctions_investigation_20250317/run_a_one_shot_conjunction_flat_swap"


resume_path: "/homes/pr450/repos/research_projects/sampling_ddpm/results_link_sampler/ddpm_conjuctions_investigation_20250317/run_a_one_shot_conjunction_flat_swap_0/state.mdl"


# Task
task_name: probe_cue_vectoral_spike_and_slab
task_config:

  sample_size: 2
  num_items: 2  # Less than Mallett
  correct_probability: 0.7
  residual_in_behaviour_plane_only: false
  sample_radius: 2.5
  
  # Like Mallett 2022, dt = 0.15
  stimulus_exposure_duration: 10  # Increased from 5 to help encoding
  pre_index_delay_duration: 15  # Decreased from 28 to help with memory
  index_duration: 5
  post_index_delay_duration: 1   # Decreased from 80 - now part of diffusion period! - see task!
