# 20250317
# One more time...

# python -m ddpm.train.multiepoch ddpm/configs/conjuctions_investigation/c_probe_cued_flat_swap_variable_delay.yaml


# Model
model_name: teacher_forced_delayed_probe_cue
model_config:
  recurrence_hidden_layers: [32]
  time_embedding_size: 16
  sample_ambient_dim: 32
  residual_model_kwargs:
    nonlin_first: false   # Keep this off!!
  ddpm_model_kwargs:
    stabilise_nullspace: true
    seperate_output_neurons: false


regularise_prep_state: true
regularise_prep_state_weight: 0.001

# Diffusion -- changed also!
ultimate_sigma2: 0.20
starting_sigma2: 0.20
num_timesteps: 40

# Training/logging
logging_freq: 1000
batch_size: 32
num_samples: 1024
num_trials: 10_000_000
lr: 0.001
save_base: "/homes/pr450/repos/research_projects/sampling_ddpm/results_link_sampler/ddpm_conjuctions_investigation_20250317/run_c2_probe_cued_flat_swap_variable_delay_smaller"


resume_path: "/homes/pr450/repos/research_projects/sampling_ddpm/results_link_sampler/ddpm_conjuctions_investigation_20250317/run_c2_probe_cued_flat_swap_variable_delay_smaller_4/state.mdl"


# Task
task_name: delayed_probe_cue_vectoral_spike_and_slab
task_config:

  sample_size: 2
  num_items: 2  # Less than Mallett
  correct_probability: 0.7
  residual_in_behaviour_plane_only: false
  sample_radius: 2.5

  cue_with_report: false
  
  # Like Mallett 2022, dt = 0.15
  stimulus_exposure_duration: 6  # Increased from 5 to help encoding
  pre_index_delay_duration: [5, 6]  # Decreased from 28 to help with memory
  index_duration: 5
  post_index_delay_duration: 1   # Decreased from 80 - now part of diffusion period! - see task!
