run_name: '../ddpm_conjuctions_investigation_20250317/run_d_alt3_index_cued_with_swap_variable_delay_tighter_0'
num_cue_gridpoints: 0
ctd_batch_size: 1024
num_opt_steps: 50_000
save_base: '/homes/pr450/repos/research_projects/sampling_ddpm/results_link_sampler/analysis/decoder_analysis/e_alleman_analysis_index_precue'

# python analysis/decoder_analysis/e_alleman_analysis_index.py analysis/decoder_analysis/e_alleman_analysis_index/base.yaml
