# NB: this experiment makes no sense really - it is exactly the same as b2. I just want to see if sampling continuous noising trajectories will
# cripple learning efficiency or not...

# Model
model_name: teacher_forced_vectoral
model_config:
  recurrence_hidden_layers: [32, 32, 32]
  time_embedding_size: 16
  sample_ambient_dim: 2             # Again - the RNN-DDPM analogy doesn't apply here
  residual_model_kwargs:
    nonlin_first: true
  ddpm_model_kwargs:
    stabilise_nullspace: false        # No nullspace actually!
    seperate_output_neurons: false


# Diffusion
ultimate_sigma2: 0.06
starting_sigma2: 0.06
num_timesteps: 100


# Training/logging
logging_freq: 100
batch_size: 64
num_samples: 1024
num_trials: 10_000_000
lr: 0.001
save_base: "/homes/pr450/repos/research_projects/sampling_ddpm/results_link_sampler/ddpm_recoup_20250108/run_c_teacher_forced_2d_bimodal"


# Task
task_name: standard_fixed_probability_vectoral
task_config:
  sample_size: 2
  pmf: [0.6, 0.4]
  sample_radius: 2.5
  residual_in_behaviour_plane_only: false
  polar_sample: false
