# Realise the closeness to pmf = [0.5, 0.5] might be an easy way to explain the predictability of the mode against the pre-preparatory position

# Model
model_name: teacher_forced_vectoral_with_prep_time
model_config:
  recurrence_hidden_layers: [128]  # weaken model by a lot so that it has to use its nullspace activity
  time_embedding_size: 16
  sample_ambient_dim: 128             
  residual_model_kwargs:
    nonlin_first: true
  ddpm_model_kwargs:
    num_prep_steps: 20
    network_input_during_diffusion: false
    stabilise_nullspace: true
    seperate_output_neurons: false


resume_path: /homes/pr450/repos/research_projects/sampling_ddpm/results_link_sampler/ddpm_recoup_20250108/run_f_teacher_forced_more_d_bimodal_memory_2/state.mdl

regularise_prep_state: true
regularise_prep_state_weight: 0.1


# Diffusion
ultimate_sigma2: 0.06
starting_sigma2: 0.06
num_timesteps: 100


# Training/logging
logging_freq: 100
batch_size: 64
num_samples: 1024
num_trials: 10_000_000
lr: 0.001
save_base: "/homes/pr450/repos/research_projects/sampling_ddpm/results_link_sampler/ddpm_recoup_20250108/run_f2_teacher_forced_more_d_bimodal_memory_uneven"


# Task
task_name: standard_fixed_probability_vectoral
task_config:
  sample_size: 2
  pmf: [0.8, 0.2]                                 # only difference to previous!
  sample_radius: 2.5
  residual_in_behaviour_plane_only: false
  polar_sample: false
