run_name: 'run_c_index_bounce_swap_4'
ctd_batch_size: 512
num_opt_steps: 50_000
cued_feature: index
include_cuing_time: true
same_gating_across_time: true
shared_p_misbind_over_time: true
shared_p_swap_over_trials: false
postcue_only_nullspace: true
z_score: true
do_elbo: true
training_style: first_step
