# 20250203
# Basic version of Mallett 2022 task with no swapping, just diffusion to a correct answer
# Items are fed in as an *ordered* set of colours
  # These are coordinates on the unit circle
  # A location (index) may be unoccupied, in which case this is just zero
# Probes are fed in as the index of this ordered set

# TODO: later, test this model by probing an unoccupied item!
