
# Model
model_name: teacher_forced_delayed_index_cue
model_config:
  recurrence_hidden_layers: [128]
  time_embedding_size: 16
  sample_ambient_dim: 128
  indexing_embeddings_same_slots: false
  residual_model_kwargs:
    nonlin_first: true
  ddpm_model_kwargs:
    stabilise_nullspace: true
    seperate_output_neurons: false
  num_items: 2                      # Needed so we can pass index to input model during the cueing phase


regularise_prep_state: true
regularise_prep_state_weight: 0.1


# Diffusion
ultimate_sigma2: 0.2
starting_sigma2: 0.2
num_timesteps: 40

# Training/logging
logging_freq: 1000
batch_size: 32
num_samples: 1024
num_trials: 10_000_000
lr: 0.001
save_base: "/homes/pr450/repos/research_projects/sampling_ddpm/results_link_sampler/ddpm_further_20250120/run_c2_revisit_index_cuing_improved_schedule"


# resume_path: '/homes/pr450/repos/research_projects/sampling_ddpm/results_link_sampler/ddpm_further_20250120/run_b2_probe_cued_with_probe_flat_swap_fewer_variable_delay_0/state.mdl'
# resume_kept_input_dims: [4, 5, 6, 7, 8, 9]
resume_path: '/homes/pr450/repos/research_projects/sampling_ddpm/results_link_sampler/ddpm_further_20250120/run_c2_revisit_index_cuing_improved_schedule_0/state.mdl'


# Task
task_name: delayed_indexing_cue_fixed_probability_vectoral
task_config:
  sample_size: 2
  sample_radius: 2.5

  # Like Mallett 2022, dt = 0.15
  stimulus_exposure_duration: 10  # Increased from 5 to help encoding
  pre_index_delay_duration: [15, 30]  # Decreased from 28 to help with memory
  index_duration: 5
  post_index_delay_duration: 1   # Decreased from 80 - now part of diffusion period! - see task!

  residual_in_behaviour_plane_only: false
  num_items: 2
  correct_probability: 0.7
